#!/usr/bin/env bash
#This script uses while loop and if
sayhi=1
	while [ $sayhi -le 10 ]
		do
		    echo "Best School"	
		if [ $sayhi -eq 9 ]
			then
				echo "Hi"
		fi

		((sayhi++))
		#echo $sayhi
	done
