#!/usr/bin/env bash
#This script displays numbers from 1 to 20 and displays specific text in between
supersti=1
	while [ $supersti -le 20 ]
		do
	
	echo $supersti
	case $supersti in
		
			4)
			echo "bad luck from China"
			;;
			9)
			echo "bad luck from Japan"
			;;
			17)
			echo "bad luck from Italy"
			;;
		esac
	((supersti++))
	done
